@startuml
package "com.example" {
  class User {
    -name : String
    -age : int
    +getName() : String
    +setName(String) : void
  }

  class Employee {
    -employeeId : String
    +getId() : String
  }
  User <|-- Employee
  Identifiable <|.. Employee

  interface Identifiable {
    ~getId() : String
  }

  class Product {
    +id : String
    +name : String
    +display() : Unit
  }

  class Shape {
    +area() : Double
  }

  class Circle {
    +radius : Double
    +area() : Double
  }
  Shape <|-- Circle

  object AppConfig {
    +version : Any
  }

}

@enduml